language: "node_js"
node_js:
  - "16"
  - "14"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "3" # io.js
  - "2" # io.js
  - "1" # io.js
  - "0.12"
  - "0.10"


script:
  - "npm i"
  - "npm run build"
  - "npm run lint"
  - "npm run typecheck"
  - "npm run test"

sudo: false
